template_files:
  default_template: |
    {{ define "sns.default.message" }}{{ .CommonAnnotations.SortedPairs.Values | join " " }}
      {{ if gt (len .Alerts.Firing) 0 -}}
      
      *** ALERTS FIRING ***:

        {{ range .Alerts.Firing }}Labels:
        {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
        {{ end }}Annotations:
        {{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}
        {{ end }}{{"\n"}}{{ end }}

      {{- end }} 
    {{- end }}
alertmanager_config: |
  global:
  templates:
    - 'default_template'
  route:
    receiver: 'default'
    group_by: [alertname]
  receivers:
    - name: 'default'
      sns_configs:
      - topic_arn: arn:aws:sns:us-east-1:****:NotifyMe
        send_resolved: false
        sigv4:
          region: us-east-1
        attributes:
          key: severity
          value: SEV2