alertmanager_config: |
  route:
    receiver: 'default'
  receivers:
    - name: 'default'
      sns_configs:
      - topic_arn: arn:aws:sns:us-east-1:****:sp****-kc1-prd-iad-amp
        sigv4:
          region: us-east-1
        attributes:
          key: severity
          value: SEV2
